// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuweeQD1OdVdTamLQCozkYjN5r6MZHCjE',
    appId: '1:243080209943:web:a51816f20e1d37cce8de52',
    messagingSenderId: '243080209943',
    projectId: 'feeds-ff990',
    authDomain: 'feeds-ff990.firebaseapp.com',
    storageBucket: 'feeds-ff990.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwLjR-wHERhLFBOQBdZb0dIR6fxoP_V8',
    appId: '1:243080209943:android:a5e577aa84fdf873e8de52',
    messagingSenderId: '243080209943',
    projectId: 'feeds-ff990',
    storageBucket: 'feeds-ff990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIUlqxPkpWls7sKEFblW2gwAiuGFywc98',
    appId: '1:243080209943:ios:b288ee47ae314b60e8de52',
    messagingSenderId: '243080209943',
    projectId: 'feeds-ff990',
    storageBucket: 'feeds-ff990.appspot.com',
    androidClientId: '243080209943-44rkov7it417urkq4ju88m7fr52916h6.apps.googleusercontent.com',
    iosClientId: '243080209943-j9lt0fksr6mfjcq837k1rb40aso5vqub.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIUlqxPkpWls7sKEFblW2gwAiuGFywc98',
    appId: '1:243080209943:ios:b288ee47ae314b60e8de52',
    messagingSenderId: '243080209943',
    projectId: 'feeds-ff990',
    storageBucket: 'feeds-ff990.appspot.com',
    androidClientId: '243080209943-44rkov7it417urkq4ju88m7fr52916h6.apps.googleusercontent.com',
    iosClientId: '243080209943-j9lt0fksr6mfjcq837k1rb40aso5vqub.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
